name: Backend Tests
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - resources/assets/**
  push:
    branches:
      - main
    paths-ignore:
      - resources/assets/**
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - resources/assets/**
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ 8.2 ]
      fail-fast: false
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
          coverage: xdebug
          extensions: pdo_sqlite, zip, gd
      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Generate app key
        run: php artisan key:generate --quiet
      - name: Run code style checker
        run: composer pint -- --test
      - name: Run static analysis
        run: composer analyse -- --no-progress
      - name: Run PHP insight
        run: composer insight-action
      - name: Run tests
        run: composer test
      - name: Attempt Swagger Generation
        run: composer swagger
      - name: Upload logs if broken
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: storage/logs
